# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ForPigPyo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForPigPyo
	pod 'SwiftLint'
	pod 'SnapKit', '~> 5.0.0'
	pod 'Google-Mobile-Ads-SDK'

	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'

end
