# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ForPigPyo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForPigPyo
	
	#Rx
	pod 'Moya/RxSwift', '~> 15.0.0'
	pod 'RxCocoa', '~> 6.2.0'
	pod 'RxGesture', '~> 4.0.2'
	pod 'RxDataSources', '~> 5.0'
	pod 'RxOptional'
	
	#util
	pod 'SwiftLint'
	pod 'Then'
	pod 'SnapKit', '~> 5.0.0'

	#Google
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'
	pod 'Firebase/Analytics'
	pod 'Firebase/Crashlytics'
	pod 'Google-Mobile-Ads-SDK'

end
