# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ForPigPyo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ForPigPyo
	pod 'SnapKit', '~> 5.0.0'
	pod 'Google-Mobile-Ads-SDK'
	pod 'SwiftLint'

end
